
import { AppConfig } from './types';

export const INITIAL_CONFIG: AppConfig = {
  fontImportUrl: '',
  fontFamilyName: '',
  userStyles: [],
  foundation: {
    bodyBgColor: '#111827',
    messageBufferBgColor: '#1F2937',
    timestampColor: '#9CA3AF',
    ownerColor: '#F9FAFB',
    pollWellBgColor: 'transparent',
    pollWellColor: '#D1D5DB',
    queueItemBorder: true,
    navbarBgColor: 'rgba(31, 41, 55, 0.5)',
    chatTextColor: '#D1D5DB',
    linkColor: '#818CF8',
    userlistBgColor: '#1F2937',
    userlistTextColor: '#E5E7EB',
    queueActiveBgColor: '#4F46E5',
    queueActiveTextColor: '#FFFFFF',
  },
  motd: {
    title: '',
    subtitle: '',
    backgroundImageUrl: '',
    titleColor: '#FFFFFF',
    titleFontSize: '100px',
    titleTextShadow: '2px 2px 8px #000000',
    subtitleColor: '#FFFFFF',
    subtitleFontSize: '50px',
    subtitleTextShadow: '2px 2px 4px #000000',
  },
  advancedCss: '',
  javascript: {
    welcomeMessage: '',
    enableCinematicMode: false,
    enableMouseFollower: false,
    enableRandomThemeButton: false,
    enableSimpsonsGame: false,
    enableFloatingImages: false,
    floatingImageUrls: [
      'https://static.wikia.nocookie.net/fictionalcompanies/images/e/e9/Kwik-E-Mart_logo.png',
      'https://static.wikia.nocookie.net/simpsonstappedout/images/a/ad/Monster_Couch_Menu.png',
      'https://www.seekpng.com/png/full/824-8246039_simpsons-donut-png.png',
      'https://www.pngall.com/wp-content/uploads/8/The-Simpsons-Logo-PNG.png',
      'https://i.pinimg.com/originals/e5/3d/76/e53d76ac61eeef46beba0df53edde30f.png',
      'https://www.universalorlando.com/webdata/k2/en/gb/files/Images/usf-springfield-usa-logo-no-bg-b.png'
    ].join(',\n'),
    enableChristmasSnow: false,
    enableChristmasCursor: false,
    enableMatrixRain: false,
    enableVideowrapShake: false,
    enableGlowyGrid: false,
    enableVideoFollowCursor: false,
  },
  cssEffects: {
    pulsatingVideowrapBorder: false,
    animatedBackground: false,
    customScrollbars: false,
    videowrapTvScanlines: false,
    videowrapVhsGlitch: false,
    videowrapFloatingFrame: false,
    videowrapFilmBorder: false,
    pulsatingMotdBackground: false,
    animatedQueue: false,
    cinematicBlackBars: false,
    animatedBackgroundNebula: false,
    animatedBackgroundPulsatingGrid: false,
    animatedBackgroundFloatingBlobs: false,
    videowrapNightVision: false,
    videowrapSecurityCamera: false,
    videowrapHolographic: false,
    videowrapSepiaFilm: false,
    videowrapCrtEffect: false,
    videowrapSignalInterference: false,
    videowrapPulsatingGlow: false,
    videowrapOldTVStartup: false,
    videowrapStaticNoise: false,
    videowrapGlitchEffect: false,
    videowrapFilmGrain: false,
    simpsonsCloudBackground: false,
    simpsonsTvFrame: false,
    invertColors: false,
    creepyTextShadow: false,
    dramaticLighting: false,
    spookyFogOverlay: false,
    staticNoiseBackground: false,
    christmasLightsHeader: false,
    letItSnow: false,
    animatedQueueNowPlaying: false,
    playlistHoverGlitchText: false,
    playlistSlideInOnLoad: false,
    playlistItemSpotlight: false,
  },
};

export const GOOGLE_FONTS_OPTIONS = [
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Inter',
  'Poppins',
  'Playfair Display',
  'Fira Code',
  'Bebas Neue',
  'Lobster',
  'Pacifico',
  'Gloria Hallelujah',
  'VT323',
  'Press Start 2P',
];